### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by zivagolee** [jcsalterego/historian#1]
Got these errors on import:

/Users/user/.bash_history:484: expected 1 columns but found 3 - extras ignored

This line has:

i2cssh -2 -A -l user `for i in $(seq -f %02g 1 8); do echo -n "server$i-use1 " ; done`

I'm guessing it is having issues on the quotes or backticks.

**Comment by jcsalterego** [comment]
Ack. That's because I use backticks for sqlite's delimiter during import. My bad! I'll figure something out soon. Thanks for the bug report!

**Comment by mchampanis** [comment]
I had the same problem with a line in my `.bash_history` with backticks. I also had a few `.bash_history:6: unescaped " character` errors for lines when I had done something like:

`git commit -am "message with no closing double quote` 

and then ctrl-c'd or similar to cancel, but the line was still recorded without the closing `"`

**Comment by evolarjun** [comment]
I had the same problem:
    $ hist import
    Error: /home/aprasad/.bash_history line 406: expected 1 columns of data but found 3
    Imported 0 item(s).

    $ awk 'NR == 406{print}' ~/.bash_history
    for file in `ls *.tsv`; do grep -c -v DNA $file; done > dnacounts

I fixed it using some random characters copied from /dev/urandom

    $ diff hist hist.orig
    84c84
    < .separator \`
    --- 
    > .separator \`coS^k\(bR%\)~uZ\)AYL\&9@qL&z,TP
    $ hist import
    Imported 5888 item(s).

Thanks for the script, I'm not sure my solution works since I can't search. I know nothing about SQLite, but this is an opportunity to figure it out.

**Comment by jcsalterego** [comment]
@evolarjun very interesting - what version of sqlite3 do you have? I had tried that before and became saddened:

```
Error: multi-character column separators not allowed for import
```

Mine is

```$ sqlite3 --version
3.15.0 2016-10-14 10:20:30 707875582fcba352b4906a595ad89198d84711d8
```

**Comment by zivagolee** [comment]
This definitely does not work with sqlite3 3.16.0 (latest in brew)

**Comment by evolarjun** [comment]
$ sqlite3 --version
    3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668

That's just what was installed by default by our sysadmins at work. I'm somewhat surprised it's that up-to-date.

**Comment by evolarjun** [comment]
The other problem I had was lots of my commands have " characters in them and that was messing things up. I fixed it by adding a perl one-liner and a quick-n-dirty tempfile to the import. 

    $ diff hist.orig hist
    77c77
    <
    ---
    >     perl -pe 's#"#""#g' "${SRC}" > "${SRC}.tmp"
    84,85c84,85
    < .separator \`
    < .import ${SRC} history_import
    ---
    > .separator \`coS^k\(bR%\)~uZ\)AYL\&9@qL&z,TP
    > .import ${SRC}.tmp history_import

I should use mktemp and clean up after myself, but I have to get some work done :-)

**Comment by jcsalterego** [comment]
I believe the import separator issue is fixed now.

**Comment by maxmcd** [comment]
A single quote `"` still triggers this error
```
/Users/maxm/.bash_history:3436: unescaped " character
/Users/maxm/.bash_history:3889: unterminated "-quoted field
```
Seems to depending on the presence of surrounding quote characters in the bash history

**Comment by jcsalterego** [comment]
@maxmcd Thanks - do you mind opening a new issue specific to quotation marks and we'll track it there?
