### ISSUE TITLE
A single quote in .bash_history triggers an error

### ISSUE THREAD

**Issue by maxmcd** [jcsalterego/historian#14]
A single quote `"` triggers an error

```
/Users/maxm/.bash_history:3436: unescaped " character
/Users/maxm/.bash_history:3889: unterminated "-quoted field
```

Seems to depend somewhat on the presence of surrounding quote characters in the bash history

To reproduce, a .bash_history file containing only:
```

"
hist import

```
triggers this error

**Comment by jcsalterego** [comment]
Thanks @maxmcd. I've been able to reproduce, and this will likely require some sort of dive into sqlite's import functionality.

**Comment by jcsalterego** [comment]
@maxmcd Please grab the latest master branch -- this should be resolved.

**Comment by maxmcd** [comment]
Resolved! Thanks, works great

**Comment by jcsalterego** [comment]
@maxmcd :tada:
