### ISSUE TITLE
Import error with unescaped " character

### ISSUE THREAD

**Issue by eagleusb** [jcsalterego/historian#17]
Hello,

when I try to import my history with some lines containing the '"' character it will fail with :

```shell
/home/bob/.bash_history:156: unescaped " character
/home/bob/.bash_history:156: unescaped " character
/home/bob/.bash_history:506: unescaped " character
```

Concerned lines example :

```shell
ssh-keygen -f "/home/bob/.ssh/known_hosts" -R
```

**Comment by jcsalterego** [comment]
@gooodmorningopenstack thanks for the feedback! Do you have the latest `master` branch pulled down?

**Comment by eagleusb** [comment]
Oh dear, it seems to work with the branch `master`. I'll close this issue for now and reopen it if it happens again :)

Thanks for your work !

Bye

**Comment by jcsalterego** [comment]
@gooodmorningopenstack No problem! It should be fixed as of https://github.com/jcsalterego/historian/issues/15
