### ISSUE TITLE
unescaped " character

### ISSUE THREAD

**Issue by zivagolee** [jcsalterego/historian#18]
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18093: unescaped " character
/Users/zivago/.bash_history:18088: unterminated "-quoted field
Imported 1 item(s).

this is on historian v0.0.2. Looks like some of the items in bash history was a bad command line option. Anyway to escape them properly so it imports it?

**Comment by zivagolee** [comment]
Example of something that doesn't import:

"""""[",,

Seems to die on the commas. Maybe we can have a way to ignore and not import these if this shows up? These are likely bad commands anyway?

**Comment by jcsalterego** [comment]
Hmm, I'll have to do some testing - thanks!

**Comment by jcsalterego** [comment]
@zivagolee (Years later) Is this still an issue, or did you move on? :)

**Comment by zivagolee** [comment]
> @zivagolee (Years later) Is this still an issue, or did you move on? :)

haha, yea, it's been quite a few years so I haven't looked it since then.

**Comment by jcsalterego** [comment]
@zivagolee Thanks!
