### ISSUE TITLE
fzf / output format

### ISSUE THREAD

**Issue by notDavid** [jcsalterego/historian#19]
Hi there,

do you have any idea why historian doesn't work with [fzf](https://github.com/junegunn/fzf) ?

After installing fzf i simply changed `history` to `hist /` in https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash#L58 
and this works when searching in the history by pressing CTRL+R in the terminal. But when selecting one of the items in the list, that item doesn't get output/pasted back to the terminal.

I noticed that the output format of historian is different from the default 'history', so perhaps that is the issue?
If so, it would be cool if the output format would be equal to history, for better compatibility with other tools.

Thank you!

```
$ history | grep -i 'test 123'
  520  echo "test 123"
$
$ hist /'test 123'
1923
    echo "test 123"
$
```

**Comment by jcsalterego** [comment]
Very interesting idea! I'll tinker when I have a moment.

**Comment by jcsalterego** [comment]
@notDavid (Years later) Are you still running into this issue with `fzf` or did you move on? :)

**Comment by notDavid** [comment]
Hi there @jcsalterego, yes i moved on indeed :-) I'm now using [this via Fish](https://github.com/PatrickF1/fzf.fish#-search-history).

So feel free to close the issue if you want to.

**Comment by jcsalterego** [comment]
@notDavid Nice! Thanks
