### ISSUE TITLE
Support for zsh

### ISSUE THREAD

**Issue by djpentz** [jcsalterego/historian#2]
I use zsh. It's fairly simple to support this by making the SRC var settable. Can this be done? If so how would you suggest it, if I were to try do that myself as a PR?

**Comment by erichs** [comment]
Both bash and zsh support the `$HISTFILE` env var, which always points to the current history file.

**Comment by jcsalterego** [comment]
@djpentz Yeah I should make that variable overridable. @erichs also has a good point - maybe I just need to switch to that!

**Comment by erichs** [comment]
I'll note that on my system, HISTFILE is unexported. To make this work for my zsh, I needed to change:

```
-SRC="${HOME}/.bash_history"
+SRC="${HISTFILE}"
```

and then in my shell, do: 
```
export HISTFILE
```

**Comment by jcsalterego** [comment]
@djpentz to answer your question, I'm working on something soon!

**Comment by derekslenk** [comment]
Can't wait for ZSH support!

**Comment by jcsalterego** [comment]
@djpentz https://github.com/jcsalterego/historian/commit/05f3fa892544d4180ef346e0a3e9d18675c8f90a allows for `$HISTORIAN_SRC` to be set outside the script. Would that suffice here?

**Comment by djpentz** [comment]
Works for me. Thanks!
