### ISSUE TITLE
Homebrew Support

### ISSUE THREAD

**Issue by jamesstidard** [jcsalterego/historian#4]
Hi,

This looks great. Is it something that could be added to Homebrews repos?

Thanks.

**Comment by jcsalterego** [comment]
A kind gentleman named @kudakeru is working on it! https://github.com/Homebrew/homebrew-core/pull/12407

**Comment by jamesstidard** [comment]
@jcsalterego What a lovely chap. Thanks @kudakeru

**Comment by usrbinpikachu** [comment]
Updated the PR with their requests. Pending review now.

**Comment by jcsalterego** [comment]
Repository is too new according to CI (https://bot.brew.sh/job/homebrew-core/job/PR-12407/3/console)! It should be pass by... May 8 or so.

**Comment by usrbinpikachu** [comment]
Successfully merged! https://github.com/Homebrew/homebrew-core/pull/12407#issuecomment-295034401

**Comment by jcsalterego** [comment]
Thanks @kudakeru!
