### ISSUE TITLE
Allow updating on every bash command

### ISSUE THREAD

**Issue by Wilfred** [jcsalterego/historian#9]
```
$ hist count
183
$ ls /some/new/path
...
$ hist count
184
```

It would be nice to insert items in the database immediately. This is particularly useful when you have two terminals open.

**Comment by teranex** [comment]
I think it should be possible by using `PROMPT_COMMAND` (https://wiki.archlinux.org/index.php/Bash/Prompt_customization#PROMPT_COMMAND) and run `hist import` everytime before the prompt is shown

**Comment by jcsalterego** [comment]
While this is possible, the `hist import` function currently imports the entirety of the source file, e.g. `~/.bash_history` into a temporary table and then tries to insert (ignoring duplicates) into the main `history` table in the db file itself. This gets slower with a larger source file. Even with @teranex's solution which sounds possible, this could slow down your prompt quite a bit.

Like many people, I have `git status` in my bash prompt, but I believe running the `git` binary is much, much faster than this shell script wrapping sqlite, not to mention the slow import functionality.

**Comment by jcsalterego** [comment]
@Wilfred historian doesn't have deep integration into shell right now, but this does make me think I should make the import functionality more efficient. I'm curious to know if @teranex's suggestion work for you but other than that, I don't think I'll be baking in this functionality into historian. Thanks for your feedback!
